import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import {
  Bar, BarChart, CartesianGrid, Cell, Legend,
  Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { api } from "../api.js";
import { useAuth } from "../auth.jsx";

const ACTIVITY_COLORS = {
  WALKING: "#171717",
  WALKING_UPSTAIRS: "#404040",
  WALKING_DOWNSTAIRS: "#737373",
  SITTING: "#a3a3a3",
  STANDING: "#d4d4d4",
  LAYING: "#ff3b30",
};

const colorFor = (label) => ACTIVITY_COLORS[label] || "#525252";

function Timeline({ entries }) {
  if (entries.length === 0) return null;
  const total = entries[entries.length - 1].end_time;

  return (
    <div className="space-y-3">
      <div className="relative h-10 w-full overflow-hidden border border-line bg-paper-sub">
        {entries.map((e) => {
          const left = (e.start_time / total) * 100;
          const width = ((e.end_time - e.start_time) / total) * 100;
          return (
            <div
              key={e.window_index}
              title={`${e.activity} · ${e.start_time.toFixed(2)}–${e.end_time.toFixed(2)}s · ${(e.confidence * 100).toFixed(1)}%`}
              className="absolute top-0 h-full"
              style={{
                left: `${left}%`,
                width: `${width}%`,
                background: colorFor(e.activity),
              }}
            />
          );
        })}
      </div>
      <div className="flex justify-between font-mono text-[10px] uppercase tracking-widest text-ink-faint">
        <span>0.0s</span>
        <span>{total.toFixed(1)}s</span>
      </div>
      <div className="flex flex-wrap gap-x-4 gap-y-2 border-t border-line pt-3">
        {Object.entries(ACTIVITY_COLORS).map(([k, c]) => (
          <span
            key={k}
            className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-widest text-ink-muted"
          >
            <span className="h-2 w-2" style={{ background: c }} />
            {k}
          </span>
        ))}
      </div>
    </div>
  );
}

function InsightsCard({ token, id }) {
  const [state, setState] = useState({ status: "idle", text: "", error: null });

  const load = () => {
    setState({ status: "loading", text: "", error: null });
    api
      .getInsights(token, id)
      .then((d) => setState({ status: "ready", text: d.insights, error: null }))
      .catch((e) => setState({ status: "error", text: "", error: e.message }));
  };

  useEffect(() => {
    load();
  }, [token, id]);

  return (
    <div className="card">
      <div className="flex items-start justify-between gap-4 border-b border-line pb-4">
        <div>
          <div className="eyebrow">AI · Health insights</div>
          <h2 className="mt-1 font-mono text-lg uppercase tracking-wider text-ink">
            What this says about you
          </h2>
          <p className="mt-1 font-mono text-[11px] uppercase tracking-wider text-ink-faint">
            Generated by Groq · Llama 3.3
          </p>
        </div>
        <button
          className="btn-ghost"
          onClick={load}
          disabled={state.status === "loading"}
        >
          {state.status === "loading" ? "…" : "Regenerate"}
        </button>
      </div>

      <div className="mt-5">
        {state.status === "loading" && (
          <div className="flex items-center gap-2 font-mono text-[11px] uppercase tracking-widest text-ink-faint">
            <span className="dot bg-ink-faint animate-pulse" />
            Analyzing session…
          </div>
        )}
        {state.status === "error" && (
          <div className="border border-accent bg-accent-soft p-3 font-mono text-[11px] uppercase tracking-wider text-accent">
            {state.error}
          </div>
        )}
        {state.status === "ready" && (
          <InsightsBody text={state.text} />
        )}
      </div>
      <p className="mt-4 border-t border-line pt-3 font-mono text-[10px] uppercase tracking-widest text-ink-faint">
        Informational only — not medical advice.
      </p>
    </div>
  );
}

function InsightsBody({ text }) {
  const blocks = useMemo(() => parseMarkdown(text), [text]);
  return (
    <div className="space-y-4 text-sm leading-relaxed text-ink">
      {blocks.map((b, i) => {
        if (b.type === "h") {
          return (
            <div
              key={i}
              className="eyebrow border-b border-line pb-1"
            >
              {b.text}
            </div>
          );
        }
        if (b.type === "ul") {
          return (
            <ul key={i} className="space-y-2">
              {b.items.map((item, j) => (
                <li key={j} className="flex gap-3">
                  <span className="mt-2 inline-block h-1.5 w-1.5 shrink-0 bg-ink" />
                  <span dangerouslySetInnerHTML={{ __html: inlineMd(item) }} />
                </li>
              ))}
            </ul>
          );
        }
        return (
          <p
            key={i}
            className="text-ink-muted"
            dangerouslySetInnerHTML={{ __html: inlineMd(b.text) }}
          />
        );
      })}
    </div>
  );
}

function inlineMd(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-ink">$1</strong>')
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, '<code class="kbd">$1</code>');
}

function parseMarkdown(text) {
  const lines = text.split("\n");
  const blocks = [];
  let list = null;
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      if (list) {
        blocks.push({ type: "ul", items: list });
        list = null;
      }
      continue;
    }
    const headingMatch = line.match(/^#{1,6}\s+(.+)$/);
    const boldHeadingMatch = line.match(/^\*\*(.+?)\*\*:?\s*$/);
    if (headingMatch || boldHeadingMatch) {
      if (list) {
        blocks.push({ type: "ul", items: list });
        list = null;
      }
      blocks.push({
        type: "h",
        text: (headingMatch?.[1] || boldHeadingMatch[1]).replace(/:$/, ""),
      });
      continue;
    }
    const bulletMatch = line.match(/^[-*]\s+(.+)$/);
    if (bulletMatch) {
      list = list || [];
      list.push(bulletMatch[1]);
      continue;
    }
    if (list) {
      blocks.push({ type: "ul", items: list });
      list = null;
    }
    blocks.push({ type: "p", text: line });
  }
  if (list) blocks.push({ type: "ul", items: list });
  return blocks;
}

export default function Report() {
  const { id } = useParams();
  const { token } = useAuth();
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    api.getSession(token, id).then(setData).catch((e) => setError(e.message));
  }, [token, id]);

  const summaryRows = useMemo(() => {
    if (!data) return [];
    return Object.entries(data.summary).map(([activity, seconds]) => ({
      activity,
      seconds,
    }));
  }, [data]);

  const accuracy = useMemo(() => {
    if (!data) return null;
    const withGt = data.timeline.filter((t) => t.ground_truth);
    if (withGt.length === 0) return null;
    const hits = withGt.filter((t) => t.ground_truth === t.activity).length;
    return { hits, total: withGt.length, pct: hits / withGt.length };
  }, [data]);

  if (error) {
    return (
      <div className="border border-accent bg-accent-soft p-4 font-mono text-[11px] uppercase tracking-wider text-accent">
        {error} ·{" "}
        <Link to="/" className="underline decoration-dotted underline-offset-4">
          Back
        </Link>
      </div>
    );
  }
  if (!data)
    return (
      <div className="font-mono text-[11px] uppercase tracking-widest text-ink-faint">
        Loading…
      </div>
    );

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between border-b border-line pb-5">
        <div>
          <div className="eyebrow">Session report</div>
          <h1 className="mt-1 font-mono text-2xl uppercase tracking-wider text-ink break-all">
            {data.filename}
          </h1>
          <p className="mt-2 font-mono text-[11px] uppercase tracking-wider text-ink-faint">
            Model {data.model_version} · {data.timeline.length} windows ·{" "}
            {new Date(data.uploaded_at).toLocaleString()}
          </p>
        </div>
        <Link to="/" className="btn-ghost">
          ← Sessions
        </Link>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="card">
          <div className="eyebrow">Total windows</div>
          <div className="mt-2 font-mono text-4xl text-ink">{data.timeline.length}</div>
        </div>
        <div className="card">
          <div className="eyebrow">Activities detected</div>
          <div className="mt-2 font-mono text-4xl text-ink">{summaryRows.length}</div>
        </div>
        <div className="card">
          <div className="eyebrow">
            {accuracy ? "Match vs ground truth" : "Status"}
          </div>
          <div className="mt-2 font-mono text-4xl text-ink">
            {accuracy ? `${(accuracy.pct * 100).toFixed(1)}%` : data.status}
          </div>
          {accuracy && (
            <div className="mt-2 font-mono text-[10px] uppercase tracking-widest text-ink-faint">
              {accuracy.hits}/{accuracy.total} correct
            </div>
          )}
        </div>
      </div>

      <InsightsCard token={token} id={id} />

      <div className="card">
        <div className="border-b border-line pb-4">
          <div className="eyebrow">Activity timeline</div>
          <h2 className="mt-1 font-mono text-lg uppercase tracking-wider text-ink">
            Sequence
          </h2>
          <p className="mt-1 font-mono text-[11px] uppercase tracking-wider text-ink-faint">
            Each segment = one 2.56 s window · hover for details
          </p>
        </div>
        <div className="mt-5">
          <Timeline entries={data.timeline} />
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="card">
          <div className="eyebrow">Time per activity</div>
          <h2 className="mt-1 font-mono text-lg uppercase tracking-wider text-ink">
            Distribution · bar
          </h2>
          <div className="mt-4 h-64">
            <ResponsiveContainer>
              <BarChart data={summaryRows} margin={{ top: 8, right: 8, bottom: 30, left: 0 }}>
                <CartesianGrid strokeDasharray="2 4" stroke="#e5e5e5" vertical={false} />
                <XAxis
                  dataKey="activity"
                  tick={{ fontSize: 10, fill: "#737373", fontFamily: "ui-monospace" }}
                  interval={0}
                  angle={-20}
                  textAnchor="end"
                  height={60}
                  tickLine={false}
                  axisLine={{ stroke: "#e5e5e5" }}
                />
                <YAxis
                  unit="s"
                  tick={{ fontSize: 10, fill: "#737373", fontFamily: "ui-monospace" }}
                  tickLine={false}
                  axisLine={{ stroke: "#e5e5e5" }}
                />
                <Tooltip
                  cursor={{ fill: "#f4f4f4" }}
                  contentStyle={{
                    background: "#0a0a0a",
                    color: "#fafafa",
                    border: "none",
                    fontFamily: "ui-monospace",
                    fontSize: 11,
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                    borderRadius: 0,
                  }}
                />
                <Bar dataKey="seconds">
                  {summaryRows.map((r) => (
                    <Cell key={r.activity} fill={colorFor(r.activity)} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
        <div className="card">
          <div className="eyebrow">Share</div>
          <h2 className="mt-1 font-mono text-lg uppercase tracking-wider text-ink">
            Distribution · pie
          </h2>
          <div className="mt-4 h-64">
            <ResponsiveContainer>
              <PieChart>
                <Pie
                  data={summaryRows}
                  dataKey="seconds"
                  nameKey="activity"
                  outerRadius={80}
                  innerRadius={40}
                  paddingAngle={1}
                  stroke="#fafafa"
                  strokeWidth={2}
                  labelLine={false}
                  label={summaryRows.length <= 4 ? pieSliceLabel : false}
                >
                  {summaryRows.map((r) => (
                    <Cell key={r.activity} fill={colorFor(r.activity)} />
                  ))}
                </Pie>
                <Legend
                  verticalAlign="bottom"
                  iconType="square"
                  iconSize={8}
                  wrapperStyle={{
                    fontFamily: "ui-monospace",
                    fontSize: 10,
                    letterSpacing: "0.08em",
                    textTransform: "uppercase",
                    color: "#404040",
                  }}
                />
                <Tooltip
                  contentStyle={{
                    background: "#0a0a0a",
                    color: "#fafafa",
                    border: "none",
                    fontFamily: "ui-monospace",
                    fontSize: 11,
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                    borderRadius: 0,
                  }}
                  formatter={(v) => `${Number(v).toFixed(1)}s`}
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="card p-0">
        <div className="border-b border-line px-6 py-4">
          <div className="eyebrow">Raw</div>
          <h2 className="mt-1 font-mono text-lg uppercase tracking-wider text-ink">
            Predictions
          </h2>
        </div>
        <div className="max-h-96 overflow-auto">
          <table className="min-w-full text-sm">
            <thead className="sticky top-0 border-b border-line bg-paper-card">
              <tr className="text-left font-mono text-[10px] uppercase tracking-widest text-ink-faint">
                <th className="px-6 py-3">#</th>
                <th className="px-6 py-3">Time</th>
                <th className="px-6 py-3">Activity</th>
                <th className="px-6 py-3">Confidence</th>
                <th className="px-6 py-3">Ground truth</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {data.timeline.map((e) => {
                const correct = e.ground_truth && e.ground_truth === e.activity;
                const wrong = e.ground_truth && e.ground_truth !== e.activity;
                return (
                  <tr key={e.window_index} className={wrong ? "bg-accent-soft/40" : ""}>
                    <td className="px-6 py-2 font-mono text-[11px] text-ink-faint">
                      {e.window_index}
                    </td>
                    <td className="px-6 py-2 font-mono text-[11px] text-ink-muted">
                      {e.start_time.toFixed(2)}–{e.end_time.toFixed(2)}s
                    </td>
                    <td className="px-6 py-2">
                      <span className="inline-flex items-center gap-1.5 font-mono text-[11px] uppercase tracking-widest text-ink">
                        <span
                          className="h-2 w-2"
                          style={{ background: colorFor(e.activity) }}
                        />
                        {e.activity}
                      </span>
                    </td>
                    <td className="px-6 py-2 font-mono text-[11px] text-ink-muted">
                      {(e.confidence * 100).toFixed(1)}%
                    </td>
                    <td className="px-6 py-2 font-mono text-[11px] uppercase tracking-wider">
                      {e.ground_truth ? (
                        <span className={correct ? "text-ink" : "text-accent"}>
                          {e.ground_truth}
                        </span>
                      ) : (
                        <span className="text-ink-faint">—</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function pieSliceLabel({ cx, cy, midAngle, outerRadius, activity }) {
  const RAD = Math.PI / 180;
  const r = outerRadius + 14;
  const x = cx + r * Math.cos(-midAngle * RAD);
  const y = cy + r * Math.sin(-midAngle * RAD);
  return (
    <text
      x={x}
      y={y}
      fill="#404040"
      textAnchor={x > cx ? "start" : "end"}
      dominantBaseline="central"
      style={{
        fontSize: 10,
        fontFamily: "ui-monospace",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
      }}
    >
      {activity}
    </text>
  );
}
